/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as VisiMisiRouteImport } from './routes/visi-misi'
import { Route as TimKamiRouteImport } from './routes/tim-kami'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelawanRouteImport } from './routes/relawan'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as MediaCenterRouteImport } from './routes/media-center'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramIndexRouteImport } from './routes/program.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as MediaCenterIndexRouteImport } from './routes/media-center.index'
import { Route as EventIndexRouteImport } from './routes/event.index'
import { Route as DonateIndexRouteImport } from './routes/donate.index'
import { Route as DonasiIndexRouteImport } from './routes/donasi.index'
import { Route as DokumentasiIndexRouteImport } from './routes/dokumentasi.index'
import { Route as BeritaIndexRouteImport } from './routes/berita.index'
import { Route as ProgramSlugRouteImport } from './routes/program.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as MediaCenterVideoRouteImport } from './routes/media-center.video'
import { Route as MediaCenterFotoRouteImport } from './routes/media-center.foto'
import { Route as MediaCenterDokumenRouteImport } from './routes/media-center.dokumen'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as DonateSlugRouteImport } from './routes/donate.$slug'
import { Route as DonasiSlugRouteImport } from './routes/donasi.$slug'
import { Route as DokumentasiSlugRouteImport } from './routes/dokumentasi.$slug'
import { Route as BeritaSlugRouteImport } from './routes/berita.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin/volunteers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminQrisRouteImport } from './routes/_authenticated/admin/qris'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin/programs'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin/news'
import { Route as AuthenticatedAdminImpactStatsRouteImport } from './routes/_authenticated/admin/impact-stats'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin/homepage'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin/hero'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin/gallery'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin/faq'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminDonationsRouteImport } from './routes/_authenticated/admin/donations'
import { Route as AuthenticatedAdminDonationConfirmationsRouteImport } from './routes/_authenticated/admin/donation-confirmations'
import { Route as AuthenticatedAdminDonationCategoriesRouteImport } from './routes/_authenticated/admin/donation-categories'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin/contact'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin/campaigns'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin/branding'
import { Route as AuthenticatedAdminBankAccountsRouteImport } from './routes/_authenticated/admin/bank-accounts'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin/about'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const VisiMisiRoute = VisiMisiRouteImport.update({
  id: '/visi-misi',
  path: '/visi-misi',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKamiRoute = TimKamiRouteImport.update({
  id: '/tim-kami',
  path: '/tim-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelawanRoute = RelawanRouteImport.update({
  id: '/relawan',
  path: '/relawan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCenterRoute = MediaCenterRouteImport.update({
  id: '/media-center',
  path: '/media-center',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/program/',
  path: '/program/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCenterIndexRoute = MediaCenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaCenterRoute,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiIndexRoute = DonasiIndexRouteImport.update({
  id: '/donasi/',
  path: '/donasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentasiIndexRoute = DokumentasiIndexRouteImport.update({
  id: '/dokumentasi/',
  path: '/dokumentasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramSlugRoute = ProgramSlugRouteImport.update({
  id: '/program/$slug',
  path: '/program/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCenterVideoRoute = MediaCenterVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => MediaCenterRoute,
} as any)
const MediaCenterFotoRoute = MediaCenterFotoRouteImport.update({
  id: '/foto',
  path: '/foto',
  getParentRoute: () => MediaCenterRoute,
} as any)
const MediaCenterDokumenRoute = MediaCenterDokumenRouteImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => MediaCenterRoute,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateSlugRoute = DonateSlugRouteImport.update({
  id: '/donate/$slug',
  path: '/donate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiSlugRoute = DonasiSlugRouteImport.update({
  id: '/donasi/$slug',
  path: '/donasi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentasiSlugRoute = DokumentasiSlugRouteImport.update({
  id: '/dokumentasi/$slug',
  path: '/dokumentasi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQrisRoute = AuthenticatedAdminQrisRouteImport.update({
  id: '/qris',
  path: '/qris',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminImpactStatsRoute =
  AuthenticatedAdminImpactStatsRouteImport.update({
    id: '/impact-stats',
    path: '/impact-stats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDonationsRoute =
  AuthenticatedAdminDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDonationConfirmationsRoute =
  AuthenticatedAdminDonationConfirmationsRouteImport.update({
    id: '/donation-confirmations',
    path: '/donation-confirmations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDonationCategoriesRoute =
  AuthenticatedAdminDonationCategoriesRouteImport.update({
    id: '/donation-categories',
    path: '/donation-categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBankAccountsRoute =
  AuthenticatedAdminBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/kontak': typeof KontakRoute
  '/media-center': typeof MediaCenterRouteWithChildren
  '/mitra': typeof MitraRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/relawan': typeof RelawanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/testimonials': typeof TestimonialsRoute
  '/tim-kami': typeof TimKamiRoute
  '/visi-misi': typeof VisiMisiRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/berita/$slug': typeof BeritaSlugRoute
  '/dokumentasi/$slug': typeof DokumentasiSlugRoute
  '/donasi/$slug': typeof DonasiSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/media-center/dokumen': typeof MediaCenterDokumenRoute
  '/media-center/foto': typeof MediaCenterFotoRoute
  '/media-center/video': typeof MediaCenterVideoRoute
  '/news/$slug': typeof NewsSlugRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/berita/': typeof BeritaIndexRoute
  '/dokumentasi/': typeof DokumentasiIndexRoute
  '/donasi/': typeof DonasiIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/event/': typeof EventIndexRoute
  '/media-center/': typeof MediaCenterIndexRoute
  '/news/': typeof NewsIndexRoute
  '/program/': typeof ProgramIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/donation-categories': typeof AuthenticatedAdminDonationCategoriesRoute
  '/admin/donation-confirmations': typeof AuthenticatedAdminDonationConfirmationsRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/impact-stats': typeof AuthenticatedAdminImpactStatsRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/kontak': typeof KontakRoute
  '/mitra': typeof MitraRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/relawan': typeof RelawanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/testimonials': typeof TestimonialsRoute
  '/tim-kami': typeof TimKamiRoute
  '/visi-misi': typeof VisiMisiRoute
  '/volunteer': typeof VolunteerRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/dokumentasi/$slug': typeof DokumentasiSlugRoute
  '/donasi/$slug': typeof DonasiSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/media-center/dokumen': typeof MediaCenterDokumenRoute
  '/media-center/foto': typeof MediaCenterFotoRoute
  '/media-center/video': typeof MediaCenterVideoRoute
  '/news/$slug': typeof NewsSlugRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/berita': typeof BeritaIndexRoute
  '/dokumentasi': typeof DokumentasiIndexRoute
  '/donasi': typeof DonasiIndexRoute
  '/donate': typeof DonateIndexRoute
  '/event': typeof EventIndexRoute
  '/media-center': typeof MediaCenterIndexRoute
  '/news': typeof NewsIndexRoute
  '/program': typeof ProgramIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/donation-categories': typeof AuthenticatedAdminDonationCategoriesRoute
  '/admin/donation-confirmations': typeof AuthenticatedAdminDonationConfirmationsRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/impact-stats': typeof AuthenticatedAdminImpactStatsRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/kontak': typeof KontakRoute
  '/media-center': typeof MediaCenterRouteWithChildren
  '/mitra': typeof MitraRoute
  '/partners': typeof PartnersRoute
  '/programs': typeof ProgramsRoute
  '/relawan': typeof RelawanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/testimonials': typeof TestimonialsRoute
  '/tim-kami': typeof TimKamiRoute
  '/visi-misi': typeof VisiMisiRoute
  '/volunteer': typeof VolunteerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/berita/$slug': typeof BeritaSlugRoute
  '/dokumentasi/$slug': typeof DokumentasiSlugRoute
  '/donasi/$slug': typeof DonasiSlugRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/media-center/dokumen': typeof MediaCenterDokumenRoute
  '/media-center/foto': typeof MediaCenterFotoRoute
  '/media-center/video': typeof MediaCenterVideoRoute
  '/news/$slug': typeof NewsSlugRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/berita/': typeof BeritaIndexRoute
  '/dokumentasi/': typeof DokumentasiIndexRoute
  '/donasi/': typeof DonasiIndexRoute
  '/donate/': typeof DonateIndexRoute
  '/event/': typeof EventIndexRoute
  '/media-center/': typeof MediaCenterIndexRoute
  '/news/': typeof NewsIndexRoute
  '/program/': typeof ProgramIndexRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/donation-categories': typeof AuthenticatedAdminDonationCategoriesRoute
  '/_authenticated/admin/donation-confirmations': typeof AuthenticatedAdminDonationConfirmationsRoute
  '/_authenticated/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/impact-stats': typeof AuthenticatedAdminImpactStatsRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/kontak'
    | '/media-center'
    | '/mitra'
    | '/partners'
    | '/programs'
    | '/relawan'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tentang-kami'
    | '/testimoni'
    | '/testimonials'
    | '/tim-kami'
    | '/visi-misi'
    | '/volunteer'
    | '/admin'
    | '/berita/$slug'
    | '/dokumentasi/$slug'
    | '/donasi/$slug'
    | '/donate/$slug'
    | '/event/$slug'
    | '/kategori/$slug'
    | '/media-center/dokumen'
    | '/media-center/foto'
    | '/media-center/video'
    | '/news/$slug'
    | '/program/$slug'
    | '/berita/'
    | '/dokumentasi/'
    | '/donasi/'
    | '/donate/'
    | '/event/'
    | '/media-center/'
    | '/news/'
    | '/program/'
    | '/admin/about'
    | '/admin/bank-accounts'
    | '/admin/branding'
    | '/admin/campaigns'
    | '/admin/contact'
    | '/admin/donation-categories'
    | '/admin/donation-confirmations'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/impact-stats'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/programs'
    | '/admin/qris'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/kontak'
    | '/mitra'
    | '/partners'
    | '/programs'
    | '/relawan'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tentang-kami'
    | '/testimoni'
    | '/testimonials'
    | '/tim-kami'
    | '/visi-misi'
    | '/volunteer'
    | '/berita/$slug'
    | '/dokumentasi/$slug'
    | '/donasi/$slug'
    | '/donate/$slug'
    | '/event/$slug'
    | '/kategori/$slug'
    | '/media-center/dokumen'
    | '/media-center/foto'
    | '/media-center/video'
    | '/news/$slug'
    | '/program/$slug'
    | '/berita'
    | '/dokumentasi'
    | '/donasi'
    | '/donate'
    | '/event'
    | '/media-center'
    | '/news'
    | '/program'
    | '/admin/about'
    | '/admin/bank-accounts'
    | '/admin/branding'
    | '/admin/campaigns'
    | '/admin/contact'
    | '/admin/donation-categories'
    | '/admin/donation-confirmations'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/impact-stats'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/programs'
    | '/admin/qris'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/volunteers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/kontak'
    | '/media-center'
    | '/mitra'
    | '/partners'
    | '/programs'
    | '/relawan'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tentang-kami'
    | '/testimoni'
    | '/testimonials'
    | '/tim-kami'
    | '/visi-misi'
    | '/volunteer'
    | '/_authenticated/admin'
    | '/berita/$slug'
    | '/dokumentasi/$slug'
    | '/donasi/$slug'
    | '/donate/$slug'
    | '/event/$slug'
    | '/kategori/$slug'
    | '/media-center/dokumen'
    | '/media-center/foto'
    | '/media-center/video'
    | '/news/$slug'
    | '/program/$slug'
    | '/berita/'
    | '/dokumentasi/'
    | '/donasi/'
    | '/donate/'
    | '/event/'
    | '/media-center/'
    | '/news/'
    | '/program/'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/bank-accounts'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/donation-categories'
    | '/_authenticated/admin/donation-confirmations'
    | '/_authenticated/admin/donations'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/impact-stats'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/qris'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/volunteers'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  KontakRoute: typeof KontakRoute
  MediaCenterRoute: typeof MediaCenterRouteWithChildren
  MitraRoute: typeof MitraRoute
  PartnersRoute: typeof PartnersRoute
  ProgramsRoute: typeof ProgramsRoute
  RelawanRoute: typeof RelawanRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangKamiRoute: typeof TentangKamiRoute
  TestimoniRoute: typeof TestimoniRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TimKamiRoute: typeof TimKamiRoute
  VisiMisiRoute: typeof VisiMisiRoute
  VolunteerRoute: typeof VolunteerRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  DokumentasiSlugRoute: typeof DokumentasiSlugRoute
  DonasiSlugRoute: typeof DonasiSlugRoute
  DonateSlugRoute: typeof DonateSlugRoute
  EventSlugRoute: typeof EventSlugRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProgramSlugRoute: typeof ProgramSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  DokumentasiIndexRoute: typeof DokumentasiIndexRoute
  DonasiIndexRoute: typeof DonasiIndexRoute
  DonateIndexRoute: typeof DonateIndexRoute
  EventIndexRoute: typeof EventIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visi-misi': {
      id: '/visi-misi'
      path: '/visi-misi'
      fullPath: '/visi-misi'
      preLoaderRoute: typeof VisiMisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kami': {
      id: '/tim-kami'
      path: '/tim-kami'
      fullPath: '/tim-kami'
      preLoaderRoute: typeof TimKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relawan': {
      id: '/relawan'
      path: '/relawan'
      fullPath: '/relawan'
      preLoaderRoute: typeof RelawanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-center': {
      id: '/media-center'
      path: '/media-center'
      fullPath: '/media-center'
      preLoaderRoute: typeof MediaCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/': {
      id: '/program/'
      path: '/program'
      fullPath: '/program/'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-center/': {
      id: '/media-center/'
      path: '/'
      fullPath: '/media-center/'
      preLoaderRoute: typeof MediaCenterIndexRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/': {
      id: '/donate/'
      path: '/donate'
      fullPath: '/donate/'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi/': {
      id: '/donasi/'
      path: '/donasi'
      fullPath: '/donasi/'
      preLoaderRoute: typeof DonasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumentasi/': {
      id: '/dokumentasi/'
      path: '/dokumentasi'
      fullPath: '/dokumentasi/'
      preLoaderRoute: typeof DokumentasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$slug': {
      id: '/program/$slug'
      path: '/program/$slug'
      fullPath: '/program/$slug'
      preLoaderRoute: typeof ProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-center/video': {
      id: '/media-center/video'
      path: '/video'
      fullPath: '/media-center/video'
      preLoaderRoute: typeof MediaCenterVideoRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/media-center/foto': {
      id: '/media-center/foto'
      path: '/foto'
      fullPath: '/media-center/foto'
      preLoaderRoute: typeof MediaCenterFotoRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/media-center/dokumen': {
      id: '/media-center/dokumen'
      path: '/dokumen'
      fullPath: '/media-center/dokumen'
      preLoaderRoute: typeof MediaCenterDokumenRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/$slug': {
      id: '/donate/$slug'
      path: '/donate/$slug'
      fullPath: '/donate/$slug'
      preLoaderRoute: typeof DonateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi/$slug': {
      id: '/donasi/$slug'
      path: '/donasi/$slug'
      fullPath: '/donasi/$slug'
      preLoaderRoute: typeof DonasiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumentasi/$slug': {
      id: '/dokumentasi/$slug'
      path: '/dokumentasi/$slug'
      fullPath: '/dokumentasi/$slug'
      preLoaderRoute: typeof DokumentasiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/volunteers': {
      id: '/_authenticated/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AuthenticatedAdminVolunteersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/qris': {
      id: '/_authenticated/admin/qris'
      path: '/qris'
      fullPath: '/admin/qris'
      preLoaderRoute: typeof AuthenticatedAdminQrisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/impact-stats': {
      id: '/_authenticated/admin/impact-stats'
      path: '/impact-stats'
      fullPath: '/admin/impact-stats'
      preLoaderRoute: typeof AuthenticatedAdminImpactStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/donations': {
      id: '/_authenticated/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AuthenticatedAdminDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/donation-confirmations': {
      id: '/_authenticated/admin/donation-confirmations'
      path: '/donation-confirmations'
      fullPath: '/admin/donation-confirmations'
      preLoaderRoute: typeof AuthenticatedAdminDonationConfirmationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/donation-categories': {
      id: '/_authenticated/admin/donation-categories'
      path: '/donation-categories'
      fullPath: '/admin/donation-categories'
      preLoaderRoute: typeof AuthenticatedAdminDonationCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bank-accounts': {
      id: '/_authenticated/admin/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/admin/bank-accounts'
      preLoaderRoute: typeof AuthenticatedAdminBankAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminBankAccountsRoute: typeof AuthenticatedAdminBankAccountsRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminDonationCategoriesRoute: typeof AuthenticatedAdminDonationCategoriesRoute
  AuthenticatedAdminDonationConfirmationsRoute: typeof AuthenticatedAdminDonationConfirmationsRoute
  AuthenticatedAdminDonationsRoute: typeof AuthenticatedAdminDonationsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminImpactStatsRoute: typeof AuthenticatedAdminImpactStatsRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminQrisRoute: typeof AuthenticatedAdminQrisRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVolunteersRoute: typeof AuthenticatedAdminVolunteersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
    AuthenticatedAdminBankAccountsRoute: AuthenticatedAdminBankAccountsRoute,
    AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
    AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
    AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
    AuthenticatedAdminDonationCategoriesRoute:
      AuthenticatedAdminDonationCategoriesRoute,
    AuthenticatedAdminDonationConfirmationsRoute:
      AuthenticatedAdminDonationConfirmationsRoute,
    AuthenticatedAdminDonationsRoute: AuthenticatedAdminDonationsRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
    AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
    AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
    AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
    AuthenticatedAdminImpactStatsRoute: AuthenticatedAdminImpactStatsRoute,
    AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
    AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
    AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
    AuthenticatedAdminQrisRoute: AuthenticatedAdminQrisRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MediaCenterRouteChildren {
  MediaCenterDokumenRoute: typeof MediaCenterDokumenRoute
  MediaCenterFotoRoute: typeof MediaCenterFotoRoute
  MediaCenterVideoRoute: typeof MediaCenterVideoRoute
  MediaCenterIndexRoute: typeof MediaCenterIndexRoute
}

const MediaCenterRouteChildren: MediaCenterRouteChildren = {
  MediaCenterDokumenRoute: MediaCenterDokumenRoute,
  MediaCenterFotoRoute: MediaCenterFotoRoute,
  MediaCenterVideoRoute: MediaCenterVideoRoute,
  MediaCenterIndexRoute: MediaCenterIndexRoute,
}

const MediaCenterRouteWithChildren = MediaCenterRoute._addFileChildren(
  MediaCenterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  KontakRoute: KontakRoute,
  MediaCenterRoute: MediaCenterRouteWithChildren,
  MitraRoute: MitraRoute,
  PartnersRoute: PartnersRoute,
  ProgramsRoute: ProgramsRoute,
  RelawanRoute: RelawanRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangKamiRoute: TentangKamiRoute,
  TestimoniRoute: TestimoniRoute,
  TestimonialsRoute: TestimonialsRoute,
  TimKamiRoute: TimKamiRoute,
  VisiMisiRoute: VisiMisiRoute,
  VolunteerRoute: VolunteerRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  DokumentasiSlugRoute: DokumentasiSlugRoute,
  DonasiSlugRoute: DonasiSlugRoute,
  DonateSlugRoute: DonateSlugRoute,
  EventSlugRoute: EventSlugRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProgramSlugRoute: ProgramSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  DokumentasiIndexRoute: DokumentasiIndexRoute,
  DonasiIndexRoute: DonasiIndexRoute,
  DonateIndexRoute: DonateIndexRoute,
  EventIndexRoute: EventIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ProgramIndexRoute: ProgramIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
