/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelawanRouteImport } from './routes/relawan'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramIndexRouteImport } from './routes/program.index'
import { Route as EventIndexRouteImport } from './routes/event.index'
import { Route as DonasiIndexRouteImport } from './routes/donasi.index'
import { Route as DokumentasiIndexRouteImport } from './routes/dokumentasi.index'
import { Route as BeritaIndexRouteImport } from './routes/berita.index'
import { Route as DonasiSlugRouteImport } from './routes/donasi.$slug'
import { Route as BeritaSlugRouteImport } from './routes/berita.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin/volunteers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminQrisRouteImport } from './routes/_authenticated/admin/qris'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin/programs'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin/news'
import { Route as AuthenticatedAdminImpactStatsRouteImport } from './routes/_authenticated/admin/impact-stats'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin/homepage'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin/hero'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin/gallery'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin/faq'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminDonationsRouteImport } from './routes/_authenticated/admin/donations'
import { Route as AuthenticatedAdminDonationConfirmationsRouteImport } from './routes/_authenticated/admin/donation-confirmations'
import { Route as AuthenticatedAdminDonationCategoriesRouteImport } from './routes/_authenticated/admin/donation-categories'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin/contact'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin/campaigns'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin/branding'
import { Route as AuthenticatedAdminBankAccountsRouteImport } from './routes/_authenticated/admin/bank-accounts'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin/about'

const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelawanRoute = RelawanRouteImport.update({
  id: '/relawan',
  path: '/relawan',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/program/',
  path: '/program/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIndexRoute = EventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiIndexRoute = DonasiIndexRouteImport.update({
  id: '/donasi/',
  path: '/donasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentasiIndexRoute = DokumentasiIndexRouteImport.update({
  id: '/dokumentasi/',
  path: '/dokumentasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiSlugRoute = DonasiSlugRouteImport.update({
  id: '/donasi/$slug',
  path: '/donasi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQrisRoute = AuthenticatedAdminQrisRouteImport.update({
  id: '/qris',
  path: '/qris',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminImpactStatsRoute =
  AuthenticatedAdminImpactStatsRouteImport.update({
    id: '/impact-stats',
    path: '/impact-stats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDonationsRoute =
  AuthenticatedAdminDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDonationConfirmationsRoute =
  AuthenticatedAdminDonationConfirmationsRouteImport.update({
    id: '/donation-confirmations',
    path: '/donation-confirmations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDonationCategoriesRoute =
  AuthenticatedAdminDonationCategoriesRouteImport.update({
    id: '/donation-categories',
    path: '/donation-categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBankAccountsRoute =
  AuthenticatedAdminBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/kontak': typeof KontakRoute
  '/mitra': typeof MitraRoute
  '/relawan': typeof RelawanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/berita/$slug': typeof BeritaSlugRoute
  '/donasi/$slug': typeof DonasiSlugRoute
  '/berita/': typeof BeritaIndexRoute
  '/dokumentasi/': typeof DokumentasiIndexRoute
  '/donasi/': typeof DonasiIndexRoute
  '/event/': typeof EventIndexRoute
  '/program/': typeof ProgramIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/donation-categories': typeof AuthenticatedAdminDonationCategoriesRoute
  '/admin/donation-confirmations': typeof AuthenticatedAdminDonationConfirmationsRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/impact-stats': typeof AuthenticatedAdminImpactStatsRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/kontak': typeof KontakRoute
  '/mitra': typeof MitraRoute
  '/relawan': typeof RelawanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/donasi/$slug': typeof DonasiSlugRoute
  '/berita': typeof BeritaIndexRoute
  '/dokumentasi': typeof DokumentasiIndexRoute
  '/donasi': typeof DonasiIndexRoute
  '/event': typeof EventIndexRoute
  '/program': typeof ProgramIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/donation-categories': typeof AuthenticatedAdminDonationCategoriesRoute
  '/admin/donation-confirmations': typeof AuthenticatedAdminDonationConfirmationsRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/impact-stats': typeof AuthenticatedAdminImpactStatsRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/kontak': typeof KontakRoute
  '/mitra': typeof MitraRoute
  '/relawan': typeof RelawanRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/berita/$slug': typeof BeritaSlugRoute
  '/donasi/$slug': typeof DonasiSlugRoute
  '/berita/': typeof BeritaIndexRoute
  '/dokumentasi/': typeof DokumentasiIndexRoute
  '/donasi/': typeof DonasiIndexRoute
  '/event/': typeof EventIndexRoute
  '/program/': typeof ProgramIndexRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/bank-accounts': typeof AuthenticatedAdminBankAccountsRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/donation-categories': typeof AuthenticatedAdminDonationCategoriesRoute
  '/_authenticated/admin/donation-confirmations': typeof AuthenticatedAdminDonationConfirmationsRoute
  '/_authenticated/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/impact-stats': typeof AuthenticatedAdminImpactStatsRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/qris': typeof AuthenticatedAdminQrisRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faq'
    | '/kontak'
    | '/mitra'
    | '/relawan'
    | '/reset-password'
    | '/tentang-kami'
    | '/testimoni'
    | '/admin'
    | '/berita/$slug'
    | '/donasi/$slug'
    | '/berita/'
    | '/dokumentasi/'
    | '/donasi/'
    | '/event/'
    | '/program/'
    | '/admin/about'
    | '/admin/bank-accounts'
    | '/admin/branding'
    | '/admin/campaigns'
    | '/admin/contact'
    | '/admin/donation-categories'
    | '/admin/donation-confirmations'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/impact-stats'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/programs'
    | '/admin/qris'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faq'
    | '/kontak'
    | '/mitra'
    | '/relawan'
    | '/reset-password'
    | '/tentang-kami'
    | '/testimoni'
    | '/berita/$slug'
    | '/donasi/$slug'
    | '/berita'
    | '/dokumentasi'
    | '/donasi'
    | '/event'
    | '/program'
    | '/admin/about'
    | '/admin/bank-accounts'
    | '/admin/branding'
    | '/admin/campaigns'
    | '/admin/contact'
    | '/admin/donation-categories'
    | '/admin/donation-confirmations'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/homepage'
    | '/admin/impact-stats'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/programs'
    | '/admin/qris'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/volunteers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/faq'
    | '/kontak'
    | '/mitra'
    | '/relawan'
    | '/reset-password'
    | '/tentang-kami'
    | '/testimoni'
    | '/_authenticated/admin'
    | '/berita/$slug'
    | '/donasi/$slug'
    | '/berita/'
    | '/dokumentasi/'
    | '/donasi/'
    | '/event/'
    | '/program/'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/bank-accounts'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/donation-categories'
    | '/_authenticated/admin/donation-confirmations'
    | '/_authenticated/admin/donations'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/impact-stats'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/qris'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/volunteers'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  KontakRoute: typeof KontakRoute
  MitraRoute: typeof MitraRoute
  RelawanRoute: typeof RelawanRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TentangKamiRoute: typeof TentangKamiRoute
  TestimoniRoute: typeof TestimoniRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  DonasiSlugRoute: typeof DonasiSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  DokumentasiIndexRoute: typeof DokumentasiIndexRoute
  DonasiIndexRoute: typeof DonasiIndexRoute
  EventIndexRoute: typeof EventIndexRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relawan': {
      id: '/relawan'
      path: '/relawan'
      fullPath: '/relawan'
      preLoaderRoute: typeof RelawanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/': {
      id: '/program/'
      path: '/program'
      fullPath: '/program/'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/': {
      id: '/event/'
      path: '/event'
      fullPath: '/event/'
      preLoaderRoute: typeof EventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi/': {
      id: '/donasi/'
      path: '/donasi'
      fullPath: '/donasi/'
      preLoaderRoute: typeof DonasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumentasi/': {
      id: '/dokumentasi/'
      path: '/dokumentasi'
      fullPath: '/dokumentasi/'
      preLoaderRoute: typeof DokumentasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi/$slug': {
      id: '/donasi/$slug'
      path: '/donasi/$slug'
      fullPath: '/donasi/$slug'
      preLoaderRoute: typeof DonasiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/volunteers': {
      id: '/_authenticated/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AuthenticatedAdminVolunteersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/qris': {
      id: '/_authenticated/admin/qris'
      path: '/qris'
      fullPath: '/admin/qris'
      preLoaderRoute: typeof AuthenticatedAdminQrisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/impact-stats': {
      id: '/_authenticated/admin/impact-stats'
      path: '/impact-stats'
      fullPath: '/admin/impact-stats'
      preLoaderRoute: typeof AuthenticatedAdminImpactStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/donations': {
      id: '/_authenticated/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AuthenticatedAdminDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/donation-confirmations': {
      id: '/_authenticated/admin/donation-confirmations'
      path: '/donation-confirmations'
      fullPath: '/admin/donation-confirmations'
      preLoaderRoute: typeof AuthenticatedAdminDonationConfirmationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/donation-categories': {
      id: '/_authenticated/admin/donation-categories'
      path: '/donation-categories'
      fullPath: '/admin/donation-categories'
      preLoaderRoute: typeof AuthenticatedAdminDonationCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bank-accounts': {
      id: '/_authenticated/admin/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/admin/bank-accounts'
      preLoaderRoute: typeof AuthenticatedAdminBankAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminBankAccountsRoute: typeof AuthenticatedAdminBankAccountsRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminDonationCategoriesRoute: typeof AuthenticatedAdminDonationCategoriesRoute
  AuthenticatedAdminDonationConfirmationsRoute: typeof AuthenticatedAdminDonationConfirmationsRoute
  AuthenticatedAdminDonationsRoute: typeof AuthenticatedAdminDonationsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminImpactStatsRoute: typeof AuthenticatedAdminImpactStatsRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminQrisRoute: typeof AuthenticatedAdminQrisRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVolunteersRoute: typeof AuthenticatedAdminVolunteersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
    AuthenticatedAdminBankAccountsRoute: AuthenticatedAdminBankAccountsRoute,
    AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
    AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
    AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
    AuthenticatedAdminDonationCategoriesRoute:
      AuthenticatedAdminDonationCategoriesRoute,
    AuthenticatedAdminDonationConfirmationsRoute:
      AuthenticatedAdminDonationConfirmationsRoute,
    AuthenticatedAdminDonationsRoute: AuthenticatedAdminDonationsRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
    AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
    AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
    AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
    AuthenticatedAdminImpactStatsRoute: AuthenticatedAdminImpactStatsRoute,
    AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
    AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
    AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
    AuthenticatedAdminQrisRoute: AuthenticatedAdminQrisRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  KontakRoute: KontakRoute,
  MitraRoute: MitraRoute,
  RelawanRoute: RelawanRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TentangKamiRoute: TentangKamiRoute,
  TestimoniRoute: TestimoniRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  DonasiSlugRoute: DonasiSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  DokumentasiIndexRoute: DokumentasiIndexRoute,
  DonasiIndexRoute: DonasiIndexRoute,
  EventIndexRoute: EventIndexRoute,
  ProgramIndexRoute: ProgramIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
